---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:vprince1/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: vprince/podinfo
      tag: dev-f8hpzacz
    replicaCount: 1
    hpa:
      enabled: true
      maxReplicas: 1
      cpu: 50
      memory: 256Mi
